# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: build

on:
  - push
  - pull_request

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 12.x
        cache: 'npm'
    - run: pwd ; ls -l ; ls -l docs ; ls -l docs/_includes
    - run: npm ci
    - run: pwd ; ls -l ; ls -l docs ; ls -l docs/_includes
    - run: npm run build --if-present
    - run: pwd ; ls -l ; ls -l docs ; ls -l docs/_includes
    - run: npm test
